backend:
  name: github
  repo: gabardcraft/gabardcraft.github.io
  branch: main
  auth_scope: repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Patch Notes"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
